export enum PageTypes {
    OVERVIEW = "OVERVIEW",
    SOCIAL = "SOCIAL",
    ANALYTICS = "ANALYTICS",
    MYSIPS = "MYSIPS",
    ADMIN = "ADMIN",
    UPGRADE = "UPGRADE",
    BUG = "BUG",
    SETTINGS = "SETTINGS",
    FRIENDS = "FRIENDS",
    MYGROUPS = "MYGROUPS",
    INBOX = "INBOX",
}
